Repository Horizon-Station-Coders/Horizon-Station, pull requests merged in 2024-03, with the labels that each got.

#38 The Great Role Refluffing
  Resources/Locale/en-US/job/job-description.ftl
  Resources/Locale/en-US/job/job-names.ftl
  Resources/Locale/en-US/nyanotrasen/job/job-description.ftl
  Resources/Locale/en-US/nyanotrasen/job/job-names.ftl
  Resources/Locale/en-US/prototypes/access/accesses.ftl
  Resources/Locale/en-US/prototypes/roles/antags.ftl
  Resources/Prototypes/Access/misc.yml
  Resources/Prototypes/Access/service.yml
  Resources/Prototypes/Catalog/uplink_catalog.yml
  Resources/Prototypes/DeltaV/Access/security.yml
  Resources/Prototypes/DeltaV/Access/service.yml
  Resources/Prototypes/Entities/Structures/Doors/Airlocks/access.yml
  Resources/Prototypes/Roles/Jobs/Civilian/botanist.yml
  Resources/Prototypes/Roles/Jobs/Civilian/lawyer.yml
  Resources/Prototypes/Roles/Jobs/Civilian/musician.yml
  Resources/Prototypes/Roles/Jobs/departments.yml
Labels: enhancement, removal, rebalance

#39 Gamemode Rebalances
  Resources/Prototypes/Catalog/uplink_catalog.yml
  Resources/Prototypes/GameRules/events.yml
  Resources/Prototypes/GameRules/roundstart.yml
  Resources/Prototypes/Guidebook/antagonist.yml
  Resources/Prototypes/Roles/Antags/revolutionary.yml
  Resources/Prototypes/Roles/Antags/zombie.yml
  Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
  Resources/Prototypes/Roles/Jobs/Engineering/chief_engineer.yml
  Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
  Resources/Prototypes/Roles/Jobs/Science/research_director.yml
  Resources/Prototypes/Roles/Jobs/Security/detective.yml
  Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
  Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
  Resources/Prototypes/Roles/Jobs/Security/warden.yml
  Resources/Prototypes/secret_weights.yml
  Resources/ServerInfo/Guidebook/Antagonist/Zombies.xml
Labels: removal, rebalance

#47 Species Removal
  Resources/Prototypes/Nyanotrasen/Species/Oni.yml
  Resources/Prototypes/Nyanotrasen/metempsychoticHumanoids.yml
  Resources/Prototypes/Species/arachnid.yml
Labels: removal, rebalance, lore change

#45 1984'd a lot of LRP out of the game
  Content.Shared/CardboardBox/Components/CardboardBoxComponent.cs
  Resources/Prototypes/Catalog/Fills/Crates/food.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/cola.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/gib.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/pwrgame.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/shamblersjuice.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/soda.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/spaceup.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/starkist.yml
  Resources/Prototypes/Datasets/tips.yml
  Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_fun.yml
  Resources/Prototypes/Entities/Objects/Fun/toys.yml
  Resources/Prototypes/Entities/Structures/Specific/Anomaly/anomalies.yml
  Resources/Prototypes/Nyanotrasen/Entities/Mobs/Species/felinid.yml
  Resources/Prototypes/Procedural/salvage_loot.yml
  Resources/Prototypes/Procedural/salvage_rewards.yml
  Resources/Prototypes/Recipes/Reactions/drinks.yml
  Resources/Prototypes/Recipes/Reactions/medicine.yml
Labels: removal, rebalance

#48 Removed accents, muted
  Resources/Prototypes/Body/Parts/skeleton.yml
  Resources/Prototypes/DeltaV/Traits/neutral.yml
  Resources/Prototypes/Entities/Clothing/Head/hats.yml
  Resources/Prototypes/Entities/Clothing/Head/misc.yml
  Resources/Prototypes/Entities/Clothing/Masks/masks.yml
  Resources/Prototypes/Entities/Clothing/OuterClothing/misc.yml
  Resources/Prototypes/Entities/Clothing/Uniforms/jumpsuits.yml
  Resources/Prototypes/Entities/Mobs/NPCs/shadows.yml
  Resources/Prototypes/Entities/Mobs/Player/humanoid.yml
  Resources/Prototypes/Entities/Mobs/Species/dwarf.yml
  Resources/Prototypes/Entities/Mobs/Species/moth.yml
  Resources/Prototypes/Entities/Mobs/Species/reptilian.yml
  Resources/Prototypes/Entities/Mobs/Species/skeleton.yml
  Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/bread.yml
  Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/cake.yml
  Resources/Prototypes/Traits/disabilities.yml
  Resources/Prototypes/Traits/inconveniences.yml
  Resources/Prototypes/Traits/neutral.yml
Labels: removal
